// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import CopyToClipboardController from "./copy_to_clipboard_controller"
application.register("copy-to-clipboard", CopyToClipboardController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LikeController from "./like_controller"
application.register("like", LikeController)

import MapController from "./map_controller"
application.register("map", MapController)

import SpotifyPlayerController from "./spotify_player_controller"
application.register("spotify-player", SpotifyPlayerController)

import UploadAvatarController from "./upload_avatar_controller"
application.register("upload-avatar", UploadAvatarController)
